// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchCreateMediaEntries implements pgx.CopyFromSource.
type iteratorForBatchCreateMediaEntries struct {
	rows                 []BatchCreateMediaEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateMediaEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateMediaEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ComparisonID,
		r.rows[0].MediaType,
		r.rows[0].MediaID,
		r.rows[0].MediaTitleRomaji,
		r.rows[0].MediaTitleEnglish,
		r.rows[0].MediaCoverLarge,
		r.rows[0].MediaCoverMedium,
		r.rows[0].CreatorStatus,
		r.rows[0].ComparatorStatus,
		r.rows[0].CreatorScore,
		r.rows[0].ComparatorScore,
		r.rows[0].InCreatorList,
		r.rows[0].InComparatorList,
	}, nil
}

func (r iteratorForBatchCreateMediaEntries) Err() error {
	return nil
}

func (q *Queries) BatchCreateMediaEntries(ctx context.Context, arg []BatchCreateMediaEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"media_entries"}, []string{"comparison_id", "media_type", "media_id", "media_title_romaji", "media_title_english", "media_cover_large", "media_cover_medium", "creator_status", "comparator_status", "creator_score", "comparator_score", "in_creator_list", "in_comparator_list"}, &iteratorForBatchCreateMediaEntries{rows: arg})
}

// iteratorForBatchEnqueueMediaForCaching implements pgx.CopyFromSource.
type iteratorForBatchEnqueueMediaForCaching struct {
	rows                 []BatchEnqueueMediaForCachingParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchEnqueueMediaForCaching) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchEnqueueMediaForCaching) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MediaID,
		r.rows[0].MediaType,
	}, nil
}

func (r iteratorForBatchEnqueueMediaForCaching) Err() error {
	return nil
}

func (q *Queries) BatchEnqueueMediaForCaching(ctx context.Context, arg []BatchEnqueueMediaForCachingParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"media_cache_queue"}, []string{"media_id", "media_type"}, &iteratorForBatchEnqueueMediaForCaching{rows: arg})
}
