// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comparison struct {
	ID                 int32            `json:"id"`
	CreatorUsername    string           `json:"creator_username"`
	ComparatorUsername string           `json:"comparator_username"`
	ComparisonDate     pgtype.Timestamp `json:"comparison_date"`
}
