// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	BatchCreateMediaEntries(ctx context.Context, arg []BatchCreateMediaEntriesParams) (int64, error)
	BatchEnqueueMediaForCaching(ctx context.Context, arg []BatchEnqueueMediaForCachingParams) (int64, error)
	CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error)
	CreateMediaEntry(ctx context.Context, arg CreateMediaEntryParams) (MediaEntry, error)
	EnqueueMediaForCaching(ctx context.Context, arg EnqueueMediaForCachingParams) error
	GetAllComparisons(ctx context.Context) ([]Comparison, error)
	GetAllComparisonsOnePerCombo(ctx context.Context) ([]Comparison, error)
	GetComparison(ctx context.Context, id int32) (Comparison, error)
	GetMediaCache(ctx context.Context, id int32) (MediaCache, error)
	GetMediaEntriesByComparison(ctx context.Context, comparisonID int32) ([]MediaEntry, error)
	// Get all media entries with media_cache data joined for recommendation scoring
	GetMediaEntriesWithCache(ctx context.Context, comparisonID int32) ([]GetMediaEntriesWithCacheRow, error)
	GetMediaTags(ctx context.Context, mediaID int32) ([]GetMediaTagsRow, error)
	GetOrCreateTag(ctx context.Context, name string) (Tag, error)
	GetPendingQueueItems(ctx context.Context, limit int32) ([]MediaCacheQueue, error)
	// Get media from comparator's list that creator doesn't have, excluding dropped/on-hold by comparator
	GetRecommendationCandidates(ctx context.Context, comparisonID int32) ([]GetRecommendationCandidatesRow, error)
	GetSharedEntriesByComparison(ctx context.Context, comparisonID int32) ([]MediaEntry, error)
	MarkQueueItemCompleted(ctx context.Context, id int32) error
	MarkQueueItemFailed(ctx context.Context, arg MarkQueueItemFailedParams) error
	MarkQueueItemProcessing(ctx context.Context, id int32) error
	NeedsCacheUpdate(ctx context.Context, id int32) (bool, error)
	UpsertMediaCache(ctx context.Context, arg UpsertMediaCacheParams) (MediaCache, error)
	UpsertMediaTag(ctx context.Context, arg UpsertMediaTagParams) error
}

var _ Querier = (*Queries)(nil)
