// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateMediaEntriesParams struct {
	ComparisonID      int32         `json:"comparison_id"`
	MediaType         string        `json:"media_type"`
	MediaID           int32         `json:"media_id"`
	MediaTitleRomaji  string        `json:"media_title_romaji"`
	MediaTitleEnglish pgtype.Text   `json:"media_title_english"`
	MediaCoverLarge   pgtype.Text   `json:"media_cover_large"`
	MediaCoverMedium  pgtype.Text   `json:"media_cover_medium"`
	CreatorStatus     string        `json:"creator_status"`
	ComparatorStatus  string        `json:"comparator_status"`
	CreatorScore      pgtype.Float8 `json:"creator_score"`
	ComparatorScore   pgtype.Float8 `json:"comparator_score"`
	InCreatorList     bool          `json:"in_creator_list"`
	InComparatorList  bool          `json:"in_comparator_list"`
}

type BatchEnqueueMediaForCachingParams struct {
	MediaID   int32  `json:"media_id"`
	MediaType string `json:"media_type"`
}

const createComparison = `-- name: CreateComparison :one
INSERT INTO comparisons (
    creator_username,
    comparator_username,
    creator_id,
    creator_name,
    creator_avatar_large,
    creator_avatar_medium,
    creator_episodes_watched,
    creator_minutes_watched,
    creator_chapters_read,
    creator_mean_score,
    comparator_id,
    comparator_name,
    comparator_avatar_large,
    comparator_avatar_medium,
    comparator_episodes_watched,
    comparator_minutes_watched,
    comparator_chapters_read,
    comparator_mean_score
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, creator_username, comparator_username, comparison_date, creator_id, creator_name, creator_avatar_large, creator_avatar_medium, creator_episodes_watched, creator_minutes_watched, creator_chapters_read, creator_mean_score, comparator_id, comparator_name, comparator_avatar_large, comparator_avatar_medium, comparator_episodes_watched, comparator_minutes_watched, comparator_chapters_read, comparator_mean_score
`

type CreateComparisonParams struct {
	CreatorUsername           string        `json:"creator_username"`
	ComparatorUsername        string        `json:"comparator_username"`
	CreatorID                 pgtype.Int4   `json:"creator_id"`
	CreatorName               pgtype.Text   `json:"creator_name"`
	CreatorAvatarLarge        pgtype.Text   `json:"creator_avatar_large"`
	CreatorAvatarMedium       pgtype.Text   `json:"creator_avatar_medium"`
	CreatorEpisodesWatched    pgtype.Int4   `json:"creator_episodes_watched"`
	CreatorMinutesWatched     pgtype.Int4   `json:"creator_minutes_watched"`
	CreatorChaptersRead       pgtype.Int4   `json:"creator_chapters_read"`
	CreatorMeanScore          pgtype.Float8 `json:"creator_mean_score"`
	ComparatorID              pgtype.Int4   `json:"comparator_id"`
	ComparatorName            pgtype.Text   `json:"comparator_name"`
	ComparatorAvatarLarge     pgtype.Text   `json:"comparator_avatar_large"`
	ComparatorAvatarMedium    pgtype.Text   `json:"comparator_avatar_medium"`
	ComparatorEpisodesWatched pgtype.Int4   `json:"comparator_episodes_watched"`
	ComparatorMinutesWatched  pgtype.Int4   `json:"comparator_minutes_watched"`
	ComparatorChaptersRead    pgtype.Int4   `json:"comparator_chapters_read"`
	ComparatorMeanScore       pgtype.Float8 `json:"comparator_mean_score"`
}

func (q *Queries) CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error) {
	row := q.db.QueryRow(ctx, createComparison,
		arg.CreatorUsername,
		arg.ComparatorUsername,
		arg.CreatorID,
		arg.CreatorName,
		arg.CreatorAvatarLarge,
		arg.CreatorAvatarMedium,
		arg.CreatorEpisodesWatched,
		arg.CreatorMinutesWatched,
		arg.CreatorChaptersRead,
		arg.CreatorMeanScore,
		arg.ComparatorID,
		arg.ComparatorName,
		arg.ComparatorAvatarLarge,
		arg.ComparatorAvatarMedium,
		arg.ComparatorEpisodesWatched,
		arg.ComparatorMinutesWatched,
		arg.ComparatorChaptersRead,
		arg.ComparatorMeanScore,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.CreatorUsername,
		&i.ComparatorUsername,
		&i.ComparisonDate,
		&i.CreatorID,
		&i.CreatorName,
		&i.CreatorAvatarLarge,
		&i.CreatorAvatarMedium,
		&i.CreatorEpisodesWatched,
		&i.CreatorMinutesWatched,
		&i.CreatorChaptersRead,
		&i.CreatorMeanScore,
		&i.ComparatorID,
		&i.ComparatorName,
		&i.ComparatorAvatarLarge,
		&i.ComparatorAvatarMedium,
		&i.ComparatorEpisodesWatched,
		&i.ComparatorMinutesWatched,
		&i.ComparatorChaptersRead,
		&i.ComparatorMeanScore,
	)
	return i, err
}

const createMediaEntry = `-- name: CreateMediaEntry :one
INSERT INTO media_entries (
    comparison_id,
    media_type,
    media_id,
    media_title_romaji,
    media_title_english,
    media_cover_large,
    media_cover_medium,
    creator_status,
    comparator_status,
    creator_score,
    comparator_score,
    in_creator_list,
    in_comparator_list
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, comparison_id, media_type, media_id, media_title_romaji, media_title_english, media_cover_large, media_cover_medium, creator_score, comparator_score, created_at, creator_status, comparator_status, in_creator_list, in_comparator_list
`

type CreateMediaEntryParams struct {
	ComparisonID      int32         `json:"comparison_id"`
	MediaType         string        `json:"media_type"`
	MediaID           int32         `json:"media_id"`
	MediaTitleRomaji  string        `json:"media_title_romaji"`
	MediaTitleEnglish pgtype.Text   `json:"media_title_english"`
	MediaCoverLarge   pgtype.Text   `json:"media_cover_large"`
	MediaCoverMedium  pgtype.Text   `json:"media_cover_medium"`
	CreatorStatus     string        `json:"creator_status"`
	ComparatorStatus  string        `json:"comparator_status"`
	CreatorScore      pgtype.Float8 `json:"creator_score"`
	ComparatorScore   pgtype.Float8 `json:"comparator_score"`
	InCreatorList     bool          `json:"in_creator_list"`
	InComparatorList  bool          `json:"in_comparator_list"`
}

func (q *Queries) CreateMediaEntry(ctx context.Context, arg CreateMediaEntryParams) (MediaEntry, error) {
	row := q.db.QueryRow(ctx, createMediaEntry,
		arg.ComparisonID,
		arg.MediaType,
		arg.MediaID,
		arg.MediaTitleRomaji,
		arg.MediaTitleEnglish,
		arg.MediaCoverLarge,
		arg.MediaCoverMedium,
		arg.CreatorStatus,
		arg.ComparatorStatus,
		arg.CreatorScore,
		arg.ComparatorScore,
		arg.InCreatorList,
		arg.InComparatorList,
	)
	var i MediaEntry
	err := row.Scan(
		&i.ID,
		&i.ComparisonID,
		&i.MediaType,
		&i.MediaID,
		&i.MediaTitleRomaji,
		&i.MediaTitleEnglish,
		&i.MediaCoverLarge,
		&i.MediaCoverMedium,
		&i.CreatorScore,
		&i.ComparatorScore,
		&i.CreatedAt,
		&i.CreatorStatus,
		&i.ComparatorStatus,
		&i.InCreatorList,
		&i.InComparatorList,
	)
	return i, err
}

const enqueueMediaForCaching = `-- name: EnqueueMediaForCaching :exec
INSERT INTO media_cache_queue (media_id, media_type)
VALUES ($1, $2)
ON CONFLICT (media_id) WHERE status IN ('pending', 'processing') DO NOTHING
`

type EnqueueMediaForCachingParams struct {
	MediaID   int32  `json:"media_id"`
	MediaType string `json:"media_type"`
}

func (q *Queries) EnqueueMediaForCaching(ctx context.Context, arg EnqueueMediaForCachingParams) error {
	_, err := q.db.Exec(ctx, enqueueMediaForCaching, arg.MediaID, arg.MediaType)
	return err
}

const getAllComparisons = `-- name: GetAllComparisons :many
SELECT id, creator_username, comparator_username, comparison_date, creator_id, creator_name, creator_avatar_large, creator_avatar_medium, creator_episodes_watched, creator_minutes_watched, creator_chapters_read, creator_mean_score, comparator_id, comparator_name, comparator_avatar_large, comparator_avatar_medium, comparator_episodes_watched, comparator_minutes_watched, comparator_chapters_read, comparator_mean_score FROM comparisons
ORDER BY comparison_date DESC
`

func (q *Queries) GetAllComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, getAllComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUsername,
			&i.ComparatorUsername,
			&i.ComparisonDate,
			&i.CreatorID,
			&i.CreatorName,
			&i.CreatorAvatarLarge,
			&i.CreatorAvatarMedium,
			&i.CreatorEpisodesWatched,
			&i.CreatorMinutesWatched,
			&i.CreatorChaptersRead,
			&i.CreatorMeanScore,
			&i.ComparatorID,
			&i.ComparatorName,
			&i.ComparatorAvatarLarge,
			&i.ComparatorAvatarMedium,
			&i.ComparatorEpisodesWatched,
			&i.ComparatorMinutesWatched,
			&i.ComparatorChaptersRead,
			&i.ComparatorMeanScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllComparisonsOnePerCombo = `-- name: GetAllComparisonsOnePerCombo :many
SELECT id, creator_username, comparator_username, comparison_date, creator_id, creator_name, creator_avatar_large, creator_avatar_medium, creator_episodes_watched, creator_minutes_watched, creator_chapters_read, creator_mean_score, comparator_id, comparator_name, comparator_avatar_large, comparator_avatar_medium, comparator_episodes_watched, comparator_minutes_watched, comparator_chapters_read, comparator_mean_score FROM (
    SELECT DISTINCT ON (creator_username, comparator_username) id, creator_username, comparator_username, comparison_date, creator_id, creator_name, creator_avatar_large, creator_avatar_medium, creator_episodes_watched, creator_minutes_watched, creator_chapters_read, creator_mean_score, comparator_id, comparator_name, comparator_avatar_large, comparator_avatar_medium, comparator_episodes_watched, comparator_minutes_watched, comparator_chapters_read, comparator_mean_score
    FROM comparisons
    ORDER BY creator_username, comparator_username, comparison_date DESC
) sub
ORDER BY comparison_date DESC
`

func (q *Queries) GetAllComparisonsOnePerCombo(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, getAllComparisonsOnePerCombo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUsername,
			&i.ComparatorUsername,
			&i.ComparisonDate,
			&i.CreatorID,
			&i.CreatorName,
			&i.CreatorAvatarLarge,
			&i.CreatorAvatarMedium,
			&i.CreatorEpisodesWatched,
			&i.CreatorMinutesWatched,
			&i.CreatorChaptersRead,
			&i.CreatorMeanScore,
			&i.ComparatorID,
			&i.ComparatorName,
			&i.ComparatorAvatarLarge,
			&i.ComparatorAvatarMedium,
			&i.ComparatorEpisodesWatched,
			&i.ComparatorMinutesWatched,
			&i.ComparatorChaptersRead,
			&i.ComparatorMeanScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComparison = `-- name: GetComparison :one
SELECT id, creator_username, comparator_username, comparison_date, creator_id, creator_name, creator_avatar_large, creator_avatar_medium, creator_episodes_watched, creator_minutes_watched, creator_chapters_read, creator_mean_score, comparator_id, comparator_name, comparator_avatar_large, comparator_avatar_medium, comparator_episodes_watched, comparator_minutes_watched, comparator_chapters_read, comparator_mean_score FROM comparisons
WHERE id = $1
`

func (q *Queries) GetComparison(ctx context.Context, id int32) (Comparison, error) {
	row := q.db.QueryRow(ctx, getComparison, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.CreatorUsername,
		&i.ComparatorUsername,
		&i.ComparisonDate,
		&i.CreatorID,
		&i.CreatorName,
		&i.CreatorAvatarLarge,
		&i.CreatorAvatarMedium,
		&i.CreatorEpisodesWatched,
		&i.CreatorMinutesWatched,
		&i.CreatorChaptersRead,
		&i.CreatorMeanScore,
		&i.ComparatorID,
		&i.ComparatorName,
		&i.ComparatorAvatarLarge,
		&i.ComparatorAvatarMedium,
		&i.ComparatorEpisodesWatched,
		&i.ComparatorMinutesWatched,
		&i.ComparatorChaptersRead,
		&i.ComparatorMeanScore,
	)
	return i, err
}

const getMediaCache = `-- name: GetMediaCache :one
SELECT id, type, title_romaji, title_english, cover_image_large, cover_image_medium, genres, average_score, mean_score, popularity, favourites, format, status, season_year, season, is_adult, updated_at, created_at FROM media_cache
WHERE id = $1
`

func (q *Queries) GetMediaCache(ctx context.Context, id int32) (MediaCache, error) {
	row := q.db.QueryRow(ctx, getMediaCache, id)
	var i MediaCache
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TitleRomaji,
		&i.TitleEnglish,
		&i.CoverImageLarge,
		&i.CoverImageMedium,
		&i.Genres,
		&i.AverageScore,
		&i.MeanScore,
		&i.Popularity,
		&i.Favourites,
		&i.Format,
		&i.Status,
		&i.SeasonYear,
		&i.Season,
		&i.IsAdult,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaEntriesByComparison = `-- name: GetMediaEntriesByComparison :many
SELECT id, comparison_id, media_type, media_id, media_title_romaji, media_title_english, media_cover_large, media_cover_medium, creator_score, comparator_score, created_at, creator_status, comparator_status, in_creator_list, in_comparator_list FROM media_entries
WHERE comparison_id = $1
ORDER BY media_title_romaji
`

func (q *Queries) GetMediaEntriesByComparison(ctx context.Context, comparisonID int32) ([]MediaEntry, error) {
	rows, err := q.db.Query(ctx, getMediaEntriesByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEntry{}
	for rows.Next() {
		var i MediaEntry
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.MediaType,
			&i.MediaID,
			&i.MediaTitleRomaji,
			&i.MediaTitleEnglish,
			&i.MediaCoverLarge,
			&i.MediaCoverMedium,
			&i.CreatorScore,
			&i.ComparatorScore,
			&i.CreatedAt,
			&i.CreatorStatus,
			&i.ComparatorStatus,
			&i.InCreatorList,
			&i.InComparatorList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaEntriesWithCache = `-- name: GetMediaEntriesWithCache :many
SELECT
    me.id, me.comparison_id, me.media_type, me.media_id, me.media_title_romaji, me.media_title_english, me.media_cover_large, me.media_cover_medium, me.creator_score, me.comparator_score, me.created_at, me.creator_status, me.comparator_status, me.in_creator_list, me.in_comparator_list,
    mc.genres,
    mc.average_score,
    mc.mean_score,
    mc.popularity,
    mc.favourites,
    COALESCE(
        (SELECT array_agg(t.name ORDER BY mt.rank DESC)
         FROM media_tags mt
         JOIN tags t ON mt.tag_id = t.id
         WHERE mt.media_id = me.media_id
           AND mt.is_media_spoiler = false
           AND mt.is_general_spoiler = false
         LIMIT 10),
        ARRAY[]::text[]
    ) as tag_names,
    COALESCE(
        (SELECT array_agg(mt.rank ORDER BY mt.rank DESC)
         FROM media_tags mt
         JOIN tags t ON mt.tag_id = t.id
         WHERE mt.media_id = me.media_id
           AND mt.is_media_spoiler = false
           AND mt.is_general_spoiler = false
         LIMIT 10),
        ARRAY[]::integer[]
    ) as tag_ranks
FROM media_entries me
LEFT JOIN media_cache mc ON me.media_id = mc.id
WHERE me.comparison_id = $1
ORDER BY me.media_title_romaji
`

type GetMediaEntriesWithCacheRow struct {
	MediaEntry   MediaEntry  `json:"media_entry"`
	Genres       []string    `json:"genres"`
	AverageScore pgtype.Int4 `json:"average_score"`
	MeanScore    pgtype.Int4 `json:"mean_score"`
	Popularity   pgtype.Int4 `json:"popularity"`
	Favourites   pgtype.Int4 `json:"favourites"`
	TagNames     interface{} `json:"tag_names"`
	TagRanks     interface{} `json:"tag_ranks"`
}

// Get all media entries with media_cache data joined for recommendation scoring
func (q *Queries) GetMediaEntriesWithCache(ctx context.Context, comparisonID int32) ([]GetMediaEntriesWithCacheRow, error) {
	rows, err := q.db.Query(ctx, getMediaEntriesWithCache, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaEntriesWithCacheRow{}
	for rows.Next() {
		var i GetMediaEntriesWithCacheRow
		if err := rows.Scan(
			&i.MediaEntry.ID,
			&i.MediaEntry.ComparisonID,
			&i.MediaEntry.MediaType,
			&i.MediaEntry.MediaID,
			&i.MediaEntry.MediaTitleRomaji,
			&i.MediaEntry.MediaTitleEnglish,
			&i.MediaEntry.MediaCoverLarge,
			&i.MediaEntry.MediaCoverMedium,
			&i.MediaEntry.CreatorScore,
			&i.MediaEntry.ComparatorScore,
			&i.MediaEntry.CreatedAt,
			&i.MediaEntry.CreatorStatus,
			&i.MediaEntry.ComparatorStatus,
			&i.MediaEntry.InCreatorList,
			&i.MediaEntry.InComparatorList,
			&i.Genres,
			&i.AverageScore,
			&i.MeanScore,
			&i.Popularity,
			&i.Favourites,
			&i.TagNames,
			&i.TagRanks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaTags = `-- name: GetMediaTags :many
SELECT t.id, t.name, mt.rank, mt.is_media_spoiler, mt.is_general_spoiler
FROM media_tags mt
JOIN tags t ON mt.tag_id = t.id
WHERE mt.media_id = $1
ORDER BY mt.rank DESC
`

type GetMediaTagsRow struct {
	ID               int32       `json:"id"`
	Name             string      `json:"name"`
	Rank             int32       `json:"rank"`
	IsMediaSpoiler   pgtype.Bool `json:"is_media_spoiler"`
	IsGeneralSpoiler pgtype.Bool `json:"is_general_spoiler"`
}

func (q *Queries) GetMediaTags(ctx context.Context, mediaID int32) ([]GetMediaTagsRow, error) {
	rows, err := q.db.Query(ctx, getMediaTags, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaTagsRow{}
	for rows.Next() {
		var i GetMediaTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.IsMediaSpoiler,
			&i.IsGeneralSpoiler,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPendingQueueItems = `-- name: GetPendingQueueItems :many
SELECT id, media_id, media_type, status, retry_after, attempts, created_at, updated_at FROM media_cache_queue
WHERE status = 'pending'
  AND (retry_after IS NULL OR retry_after <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingQueueItems(ctx context.Context, limit int32) ([]MediaCacheQueue, error) {
	rows, err := q.db.Query(ctx, getPendingQueueItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaCacheQueue{}
	for rows.Next() {
		var i MediaCacheQueue
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.MediaType,
			&i.Status,
			&i.RetryAfter,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecommendationCandidates = `-- name: GetRecommendationCandidates :many
SELECT
    me.id, me.comparison_id, me.media_type, me.media_id, me.media_title_romaji, me.media_title_english, me.media_cover_large, me.media_cover_medium, me.creator_score, me.comparator_score, me.created_at, me.creator_status, me.comparator_status, me.in_creator_list, me.in_comparator_list,
    mc.genres,
    mc.average_score,
    mc.mean_score,
    mc.popularity,
    mc.favourites,
    mc.format,
    mc.status as media_status,
    mc.season_year,
    mc.season,
    mc.is_adult
FROM media_entries me
LEFT JOIN media_cache mc ON me.media_id = mc.id
WHERE me.comparison_id = $1
  AND me.in_comparator_list = true
  AND me.in_creator_list = false
  AND me.comparator_status NOT IN ('DROPPED', 'PAUSED')
ORDER BY me.media_title_romaji
`

type GetRecommendationCandidatesRow struct {
	ID                int32            `json:"id"`
	ComparisonID      int32            `json:"comparison_id"`
	MediaType         string           `json:"media_type"`
	MediaID           int32            `json:"media_id"`
	MediaTitleRomaji  string           `json:"media_title_romaji"`
	MediaTitleEnglish pgtype.Text      `json:"media_title_english"`
	MediaCoverLarge   pgtype.Text      `json:"media_cover_large"`
	MediaCoverMedium  pgtype.Text      `json:"media_cover_medium"`
	CreatorScore      pgtype.Float8    `json:"creator_score"`
	ComparatorScore   pgtype.Float8    `json:"comparator_score"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	CreatorStatus     string           `json:"creator_status"`
	ComparatorStatus  string           `json:"comparator_status"`
	InCreatorList     bool             `json:"in_creator_list"`
	InComparatorList  bool             `json:"in_comparator_list"`
	Genres            []string         `json:"genres"`
	AverageScore      pgtype.Int4      `json:"average_score"`
	MeanScore         pgtype.Int4      `json:"mean_score"`
	Popularity        pgtype.Int4      `json:"popularity"`
	Favourites        pgtype.Int4      `json:"favourites"`
	Format            pgtype.Text      `json:"format"`
	MediaStatus       pgtype.Text      `json:"media_status"`
	SeasonYear        pgtype.Int4      `json:"season_year"`
	Season            pgtype.Text      `json:"season"`
	IsAdult           pgtype.Bool      `json:"is_adult"`
}

// Get media from comparator's list that creator doesn't have, excluding dropped/on-hold by comparator
func (q *Queries) GetRecommendationCandidates(ctx context.Context, comparisonID int32) ([]GetRecommendationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, getRecommendationCandidates, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecommendationCandidatesRow{}
	for rows.Next() {
		var i GetRecommendationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.MediaType,
			&i.MediaID,
			&i.MediaTitleRomaji,
			&i.MediaTitleEnglish,
			&i.MediaCoverLarge,
			&i.MediaCoverMedium,
			&i.CreatorScore,
			&i.ComparatorScore,
			&i.CreatedAt,
			&i.CreatorStatus,
			&i.ComparatorStatus,
			&i.InCreatorList,
			&i.InComparatorList,
			&i.Genres,
			&i.AverageScore,
			&i.MeanScore,
			&i.Popularity,
			&i.Favourites,
			&i.Format,
			&i.MediaStatus,
			&i.SeasonYear,
			&i.Season,
			&i.IsAdult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedEntriesByComparison = `-- name: GetSharedEntriesByComparison :many
SELECT id, comparison_id, media_type, media_id, media_title_romaji, media_title_english, media_cover_large, media_cover_medium, creator_score, comparator_score, created_at, creator_status, comparator_status, in_creator_list, in_comparator_list FROM media_entries
WHERE comparison_id = $1
  AND in_creator_list = true
  AND in_comparator_list = true
ORDER BY creator_status, media_title_romaji
`

func (q *Queries) GetSharedEntriesByComparison(ctx context.Context, comparisonID int32) ([]MediaEntry, error) {
	rows, err := q.db.Query(ctx, getSharedEntriesByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEntry{}
	for rows.Next() {
		var i MediaEntry
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.MediaType,
			&i.MediaID,
			&i.MediaTitleRomaji,
			&i.MediaTitleEnglish,
			&i.MediaCoverLarge,
			&i.MediaCoverMedium,
			&i.CreatorScore,
			&i.ComparatorScore,
			&i.CreatedAt,
			&i.CreatorStatus,
			&i.ComparatorStatus,
			&i.InCreatorList,
			&i.InComparatorList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueueItemCompleted = `-- name: MarkQueueItemCompleted :exec
UPDATE media_cache_queue
SET status = 'completed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkQueueItemCompleted(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markQueueItemCompleted, id)
	return err
}

const markQueueItemFailed = `-- name: MarkQueueItemFailed :exec
UPDATE media_cache_queue
SET status = 'failed',
    attempts = attempts + 1,
    retry_after = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkQueueItemFailedParams struct {
	ID         int32            `json:"id"`
	RetryAfter pgtype.Timestamp `json:"retry_after"`
}

func (q *Queries) MarkQueueItemFailed(ctx context.Context, arg MarkQueueItemFailedParams) error {
	_, err := q.db.Exec(ctx, markQueueItemFailed, arg.ID, arg.RetryAfter)
	return err
}

const markQueueItemProcessing = `-- name: MarkQueueItemProcessing :exec
UPDATE media_cache_queue
SET status = 'processing', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkQueueItemProcessing(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markQueueItemProcessing, id)
	return err
}

const needsCacheUpdate = `-- name: NeedsCacheUpdate :one
SELECT
    CASE
        WHEN updated_at < NOW() - INTERVAL '24 hours' THEN true
        ELSE false
    END as needs_update
FROM media_cache
WHERE id = $1
`

func (q *Queries) NeedsCacheUpdate(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, needsCacheUpdate, id)
	var needs_update bool
	err := row.Scan(&needs_update)
	return needs_update, err
}

const upsertMediaCache = `-- name: UpsertMediaCache :one
INSERT INTO media_cache (
    id, type, title_romaji, title_english, cover_image_large, cover_image_medium,
    genres, average_score, mean_score, popularity, favourites, format, status,
    season_year, season, is_adult
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    title_romaji = EXCLUDED.title_romaji,
    title_english = EXCLUDED.title_english,
    cover_image_large = EXCLUDED.cover_image_large,
    cover_image_medium = EXCLUDED.cover_image_medium,
    genres = EXCLUDED.genres,
    average_score = EXCLUDED.average_score,
    mean_score = EXCLUDED.mean_score,
    popularity = EXCLUDED.popularity,
    favourites = EXCLUDED.favourites,
    format = EXCLUDED.format,
    status = EXCLUDED.status,
    season_year = EXCLUDED.season_year,
    season = EXCLUDED.season,
    is_adult = EXCLUDED.is_adult,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, type, title_romaji, title_english, cover_image_large, cover_image_medium, genres, average_score, mean_score, popularity, favourites, format, status, season_year, season, is_adult, updated_at, created_at
`

type UpsertMediaCacheParams struct {
	ID               int32       `json:"id"`
	Type             string      `json:"type"`
	TitleRomaji      string      `json:"title_romaji"`
	TitleEnglish     pgtype.Text `json:"title_english"`
	CoverImageLarge  pgtype.Text `json:"cover_image_large"`
	CoverImageMedium pgtype.Text `json:"cover_image_medium"`
	Genres           []string    `json:"genres"`
	AverageScore     pgtype.Int4 `json:"average_score"`
	MeanScore        pgtype.Int4 `json:"mean_score"`
	Popularity       pgtype.Int4 `json:"popularity"`
	Favourites       pgtype.Int4 `json:"favourites"`
	Format           pgtype.Text `json:"format"`
	Status           pgtype.Text `json:"status"`
	SeasonYear       pgtype.Int4 `json:"season_year"`
	Season           pgtype.Text `json:"season"`
	IsAdult          pgtype.Bool `json:"is_adult"`
}

func (q *Queries) UpsertMediaCache(ctx context.Context, arg UpsertMediaCacheParams) (MediaCache, error) {
	row := q.db.QueryRow(ctx, upsertMediaCache,
		arg.ID,
		arg.Type,
		arg.TitleRomaji,
		arg.TitleEnglish,
		arg.CoverImageLarge,
		arg.CoverImageMedium,
		arg.Genres,
		arg.AverageScore,
		arg.MeanScore,
		arg.Popularity,
		arg.Favourites,
		arg.Format,
		arg.Status,
		arg.SeasonYear,
		arg.Season,
		arg.IsAdult,
	)
	var i MediaCache
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TitleRomaji,
		&i.TitleEnglish,
		&i.CoverImageLarge,
		&i.CoverImageMedium,
		&i.Genres,
		&i.AverageScore,
		&i.MeanScore,
		&i.Popularity,
		&i.Favourites,
		&i.Format,
		&i.Status,
		&i.SeasonYear,
		&i.Season,
		&i.IsAdult,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMediaTag = `-- name: UpsertMediaTag :exec
INSERT INTO media_tags (media_id, tag_id, rank, is_media_spoiler, is_general_spoiler)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (media_id, tag_id) DO UPDATE SET
    rank = EXCLUDED.rank,
    is_media_spoiler = EXCLUDED.is_media_spoiler,
    is_general_spoiler = EXCLUDED.is_general_spoiler
`

type UpsertMediaTagParams struct {
	MediaID          int32       `json:"media_id"`
	TagID            int32       `json:"tag_id"`
	Rank             int32       `json:"rank"`
	IsMediaSpoiler   pgtype.Bool `json:"is_media_spoiler"`
	IsGeneralSpoiler pgtype.Bool `json:"is_general_spoiler"`
}

func (q *Queries) UpsertMediaTag(ctx context.Context, arg UpsertMediaTagParams) error {
	_, err := q.db.Exec(ctx, upsertMediaTag,
		arg.MediaID,
		arg.TagID,
		arg.Rank,
		arg.IsMediaSpoiler,
		arg.IsGeneralSpoiler,
	)
	return err
}
