// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createComparison = `-- name: CreateComparison :one
INSERT INTO comparisons (creator_username, comparator_username)
VALUES ($1, $2)
RETURNING id, creator_username, comparator_username, comparison_date
`

type CreateComparisonParams struct {
	CreatorUsername    string `json:"creator_username"`
	ComparatorUsername string `json:"comparator_username"`
}

func (q *Queries) CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error) {
	row := q.db.QueryRow(ctx, createComparison, arg.CreatorUsername, arg.ComparatorUsername)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.CreatorUsername,
		&i.ComparatorUsername,
		&i.ComparisonDate,
	)
	return i, err
}

const deleteComparison = `-- name: DeleteComparison :exec
DELETE FROM comparisons
WHERE id = $1
`

func (q *Queries) DeleteComparison(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteComparison, id)
	return err
}

const getAllComparisons = `-- name: GetAllComparisons :many
SELECT id, creator_username, comparator_username, comparison_date FROM comparisons
ORDER BY comparison_date DESC
`

func (q *Queries) GetAllComparisons(ctx context.Context) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, getAllComparisons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUsername,
			&i.ComparatorUsername,
			&i.ComparisonDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComparison = `-- name: GetComparison :one
SELECT id, creator_username, comparator_username, comparison_date FROM comparisons
WHERE id = $1
`

func (q *Queries) GetComparison(ctx context.Context, id int32) (Comparison, error) {
	row := q.db.QueryRow(ctx, getComparison, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.CreatorUsername,
		&i.ComparatorUsername,
		&i.ComparisonDate,
	)
	return i, err
}

const getComparisonsByCreator = `-- name: GetComparisonsByCreator :many
SELECT id, creator_username, comparator_username, comparison_date FROM comparisons
WHERE creator_username = $1
ORDER BY comparison_date DESC
`

func (q *Queries) GetComparisonsByCreator(ctx context.Context, creatorUsername string) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, getComparisonsByCreator, creatorUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUsername,
			&i.ComparatorUsername,
			&i.ComparisonDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
