// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error)
	CreateSharedEntry(ctx context.Context, arg CreateSharedEntryParams) (SharedEntry, error)
	GetAllComparisons(ctx context.Context) ([]Comparison, error)
	GetComparison(ctx context.Context, id int32) (Comparison, error)
	GetMediaCache(ctx context.Context, id int32) (MediaCache, error)
	GetMediaTags(ctx context.Context, mediaID int32) ([]GetMediaTagsRow, error)
	GetOrCreateTag(ctx context.Context, name string) (Tag, error)
	GetSharedEntriesByComparison(ctx context.Context, comparisonID int32) ([]SharedEntry, error)
	UpsertMediaCache(ctx context.Context, arg UpsertMediaCacheParams) (MediaCache, error)
	UpsertMediaTag(ctx context.Context, arg UpsertMediaTagParams) error
}

var _ Querier = (*Queries)(nil)
